### ISSUE TITLE
Add Title, Pronouns, and Pronunciation to the Member Model

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#100]

**Comment by jhandel** [comment]
I am wondering if Title, Pronouns, and Pronunciation are common enough they should just be part of the member record?

@sueflay & @cchipman-tdy what do you guys think?

**Comment by cchipman-tdy** [comment]
Absolutely.

Carl Chipman
Mobile: +1 405 326 2275
Email: ***@***.******@***.***>


Teledyne Confidential; Commercially Sensitive Business Data

**Comment by jhandel** [comment]
Sounds good.. I am updating the title.. 

We should have Pronouns be a dropdown, but they can be put in app settings as a comma separated list so we don't have to get them right "first try".

**Comment by Spaarky1978** [comment]
I would suggest fir pronouns you put a field that can just be typed in. We tried drop down and did he him she her, they/them and then we got hit with a bunch of others we didn't even think about like he/them etc there were even one ls we never heard of.-FlokiOn Jul 18, 2024 8:50 AM, Josh ***@***.***> wrote:
Sounds good.. I am updating the title..
We should have Pronouns be a dropdown, but they can be put in app settings as a comma separated list so we don't have to get them right "first try".

**Comment by jhandel** [comment]
@Spaarky1978  that is why I was thinking we would put the dropdown in the App Settings (https://github.com/Ansteorra/KMP/wiki/App-Settings#memberadditionalinfo)

We can add anything we want at runtime using that feature..
