### ISSUE TITLE
Authorizations Query

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#106]
Authorized Jean Paul de Sens.  Went to Reports-Activity Authorizations.  added Armored Combat and Armored Combat Field Marshal. Clicked on submit.  Got a warning message

**Comment by jhandel** [comment]
Thanks, I see the issue and will get it patched up

![image](https://github.com/user-attachments/assets/da0d3715-29d2-45e5-b61f-b025d1624dd6)

**Comment by jhandel** [comment]
![image](https://github.com/user-attachments/assets/3d94ae1a-1e6f-4896-ba70-27957def9cf9)
Fixed, will release in the next build
