### ISSUE TITLE
Password Reset Email did not work

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#107]
Added Jeanpauldessens.  used jeanpauldens@gmail.com and sent a password reset request.  Nothing has arrived in my inbox.

**Comment by jhandel** [comment]
Emails in Dev go to our mail catcher and do not go out onto the internet...  Test emails were sent though and are in the mail catcher :-)

![image](https://github.com/user-attachments/assets/98b3942d-7e3a-4da7-ac7c-120dee3b6cc7)
