### ISSUE TITLE
Submit award rec - include &quot;leave blank if unknown&quot; for court fields

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#128]
For the Call Into Court, Court Availabiliy fields, can we update the field name to include something like 

&quot;Call Into Court (Leave blank unless you are sure&quot;&quot; type of thing.  Or maybe a distinguisher between profile-provided vs submitted provided? so that award submitters can&#039;t steamroll over blank fields in profiles.

**Comment by jhandel** [comment]
Added Unknown to the AMP seed data.
