### ISSUE TITLE
Add Award Req Event

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#163]
Branch drop down is not quick edit, still has the dashes, and won&#039;t let you type and complete.

**Comment by gustavogabaldon** [comment]
hello, i can fix this. please give me the path to file

**Comment by jhandel** [comment]
you will need to update several files in the plugin/awards section..

you will want to still sample code from around line 58 from https://github.com/Ansteorra/KMP/blob/main/app/plugins/Awards/templates/Recommendations/add.php

you will then want to update the branch field for https://github.com/Ansteorra/KMP/blob/main/app/plugins/Awards/templates/Events/add.php and https://github.com/Ansteorra/KMP/blob/main/app/plugins/Awards/templates/Events/view.php (it will be in the modal in the html near the bottom)

you then need to update the https://github.com/Ansteorra/KMP/blob/main/app/plugins/Awards/src/Controller/EventsController.php to pass in the branch list.. which you can steal examples from the RecommendationsController... specifically the Add in Recommendation will have sample code and it will need to go into the Add and View functions in the EventsColltroller.

Please submit a PR if you decide to take on this work item.
