### ISSUE TITLE
Add Link to Awardee&#039;s OP

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#167]
If the person being recommended for an award has a completed profile in AMP with their OP linked, can the OP link be added to this view? When deciding on awards, I will often check the OP to see if it has already been given or if the recipient has received another award recently.

**Comment by jhandel** [comment]
The link, when populated, is available on the recommendation view screen, edit screen, and the table views.. The only views that do not have the link are the kanban boards.. (though you can get to them by clicking edit)

Let us know which screen you are wanting to add the link to :-)
