### ISSUE TITLE
Lack of options and info

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#168]
There is no option to recommend an AoA.
The form does not request any of the submitter&#039;s info.

**Comment by jhandel** [comment]
The AoA is under the "General" option in the dropdown (last option) in the "Award Type" field

![Screenshot 2024-09-29 at 3 56 07 PM](https://github.com/user-attachments/assets/77136a86-3002-4eb0-95fd-54e0a22384d1)
