### ISSUE TITLE
Coronet Role Getting Error on To Be Scheduled List

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#169]
The Coronet role can see the To Be Scheduled List in the Award Recs module, but when clicking it, the knight with a finger comes up. I don&#039;t think the Coronet needs to see anything but the To Be Processed list.

**Comment by jhandel** [comment]
Root issue is that there is nothing to be scheduled and that causes that screen to fail... Will fix before the next deployment
