### ISSUE TITLE
Fighter Auth Card

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#170]
I never noticed the auth card flowing over the 3 &#039;card&#039; pages.  Now mind does. Looks like the marshal identifiers are now at split in the primary fighting type, so is causing some page setting that results in the multiple &#039;sides&#039;

**Comment by jhandel** [comment]
The display did slightly change in that the old system had a specific list of items per page and if you had too many authorizations they would just "fall off" the page.  The new system won't let a section "wrap" between pages so if two groups of authorizations can't fit on one page/card then they start the second section on the second card. 

We will look into optimizing the card layout...
