### ISSUE TITLE
Baronial Award Rec is misleading for newer person

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#172]
On the Submit Award Rec form, the baronial Award type only shows the Baronial Armigerous Service awards, not all of the Baronial awards.  While this makes sense, the award description should make this clear.

**Comment by jhandel** [comment]
All baronial awards currently in the system have been updated with the following text.

"Baronial Service Award that grants an Award of Arms and as such requires Crown approval."

This should help explain why they are in the system that is used for Crown approval of awards. 

It is possible in the future that the system may support Landeds to manage the rest of their awards too but that is not currently in scope.
