### ISSUE TITLE
color change

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#174]
in the permissions warrant tab. is there a was we can change the color for expired memberships to red? the purple looks close to the blue om every other line. just a small nit pick 
Darian de Shameless KRM

**Comment by Brijeshthummar02** [comment]
hello there, @AnsteorraMarshalWebAdmin i can fix this. please show me the path to the file.

**Comment by jhandel** [comment]
> hello there, @AnsteorraMarshalWebAdmin i can fix this. please show me the path to the file.

The issue will be at line 49 of https://github.com/Ansteorra/KMP/blob/main/app/templates/Reports/permissions_warrants_roster.php

Currently we are using Bootstrap's "danger" css class... we could look at another class like "warning" or something else..
