### ISSUE TITLE
Award Recommendation categories 

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#182]
Could you group all the youth awards into one category? Instead of having them split into different areas like they are now. Submitters might not know what all youth awards are to look in the other categories, but if they could just select youth and then see the options it might result in more use of the Youth awards other than the Rising Star

**Comment by jhandel** [comment]
Youth now have their own section

![image](https://github.com/user-attachments/assets/9000ac02-0641-446a-b42c-c84b4f5ee329)
