### ISSUE TITLE
Sensitive info./who can see this?

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#194]
I see that much of my personal information, address, DOB, is here. Who can see this?

**Comment by jhandel** [comment]
Privacy usage of AMP:

Required Fields
  SCA Name
  First Name
  Last Name
  Group
  Email Address
  Birth Month
  Birth Year

Non Required Fields
  Address
  Phone Number

Why do you need my Birth Month and Year?
  There are youth authorizations with multiple levels of age requirements, and adult authorizations that youth can not submit for.
  Also access to the site for youth requires validation with a parent account if the user registration is under 18.

Why the Additional Fields:
  Those individuals taking on roles that required Warranting are required to have their information in the system
          Authorizing Marshals
          Officers (future functionality)
          Admins of the AMP solution
          Kingdom level Martial Activity Officers
          Crown, Coronet, etc…

Who can see what?
  During the submission of an award the following information can be seen:
        SCA Name
        Additional Information from the “Additional Information” Tab if populated 
        Link to OP
        Court Preferences
        Name to contact regarding court

Who can see “everything”
          Admins - To support the solution
          Crown & Coronet - To Review and Approve Warrants every 6 months
          Kingdom level officers - To Review and Approve Warrant and Warrant Reports.
