### ISSUE TITLE
Membership Card

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#196]
Will there be a way to upload a new Membership Card? I uploaded a screen shot from the Membership Portal, but would likely scan my actual card to submit to AMP.

My Auth Card says No Membership Info.

Thank you!

**Comment by jhandel** [comment]
The membership card uploaded is reviewed by the site Secretary and they verify the information and update it.. Once they have reviewed the card we actually delete it (we don't keep copies). 

From there the membership exp date is updated from a data feed we receive from corporate once ever 4 to 6 months.
