### ISSUE TITLE
Incorrect award description

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#198]
Award of Arms: A simple grant of arms, given in recognition of membership and participation in our game. This is usually, the first award given to a member.

No.... a &quot;simple grant of arms&quot; is a Grant of Arms (GoA), which can in fact be given &quot;naked&quot; (without something like the Star of Merit etc attached).  It&#039;s rarely given in Ansteorra, but has been done in the past (see https://op.ansteorra.org/awards/id/42). 

So: 
a) suggested rewording: &quot;Award of Arms: Given in recognition of membership and participation in our game. This is usually the first award given to a member.&quot;   &lt;-- also note comma in that last sentence has been removed.

b) consider adding: &quot;Grant of Arms: Given in recognition of special service, abilities, and deeds. This award is rarely given, as several awards already convey a grant of arms.&quot;

**Comment by jdsemma** [comment]
(this was me using the 'feedback' form)

**Comment by jhandel** [comment]
Zodiacus did provide a detailed list of tweaks to the descriptions and titles of some of the awards.. These requests are being processed by the crown, coronet and the team.. I'll add these comments to that internal discussion.
