### ISSUE TITLE
Misspelling of &quot;List Coordination&quot;

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#201]
Award of the Sable Crane of Ansteorra -&gt; Event Operations - Lyst Coordination

Should be spelled &quot;List&quot; (I can give you the etymology of the word if you want me fight me on this ;)  Lol)

**Comment by jhandel** [comment]
I will share this feedback with the team as we have other suggested changes we are considering as well.
