### ISSUE TITLE
Incorrect membership 

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#202]
It is an issue on the marshal side as well and I sent a email to marshal secretary but my membership is listed as expiring in 2025 but my official membership app shows 2028

**Comment by jhandel** [comment]
Please share with the marshal secretary and they can get it updated for you.  As far as us auto-updating we can only update based on the data we get from society.. However, if you have an accurate card the Secretary can always manually correct it.
