### ISSUE TITLE
In case of court info publicly available 

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#211]
Is there a hard and fast reason that in case of court information provided by the potential award recipient is publicly viewable?  We should at least notify people that their info there is viewable by anyone. 

Also, if the potential recipient has no in case of court info, the drop down boxes are a little confusing. 
&quot;Notify me&quot; might need to be rewritten as &quot;Notify recipient&quot; 

Finally, an additional &quot;Notify award nominator&quot; toggle would be nice so the person who put them in for an award might be able to see them get the award.  (Especially if they already have their in case of court info filled in)

**Comment by jhandel** [comment]
We can make these fields not visible if the receipient is found in AMP.

**Comment by cchipman-tdy** [comment]
I think there's some good advice here.  

If the recipient has filled it in, hide it from the submitter.
I do agree that "Notify award nominator" checkbox is good, but we should put a note in there that functionality on that is still "to be designed".

**Comment by jhandel** [comment]
Incase of Court information is now only editable/visible to the crown and the person who configures it on their account (in process PR)
