### ISSUE TITLE
Award Recs - sort, search, save

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#230]
Hi! I&#039;d like to request :
* Being able to sort submitted award recs by award or recipient. 
* being able to search for a specific rec
* being able to export the award recs you&#039;ve done (or have an option to email a copy to yourself?)
* Have a tie to the OP that would check to see if the award rec you submitted was granted in court

**Comment by jhandel** [comment]
This is fixed in a PR that is in process right now.
