### ISSUE TITLE
Youth Rapier Background check

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#240]
I am not seeing my background check like I did in the old system. Having an updated background check is important for youth activities.

**Comment by Chrisincr** [comment]
Is a screen shot of how it appeared in the old system available?

**Comment by jhandel** [comment]
The background check is near the bottom of the profile detail list, its roughly the 12th field (or 13th row) of the top of the top detail section of the profile.
