### ISSUE TITLE
Parent not linking correctly

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#253]
While linking this youth account to their parent&#039;s account (Scot Eddy) the system changed the account to Verified but shows &quot;no parent assigned&quot; instead of &quot;Jovian Skleros&quot; which is the Sca name that should be showing for Scot Eddy.

**Comment by jhandel** [comment]
found the issue... 17 year olds were getting treated as adults in the system...  (but the UI was showing them as youth)..

Next release will treat 17 year olds as minors...
