### ISSUE TITLE
Confusing specialty titles for Sable Crane

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#262]
When submitting someone for a Sable Crane, I was confused by the specialties. They&#039;re all very specific, and none of them seemed to describe someone who shows up at events and consistently works hard and pitches in to help, even at events his group didn&#039;t sponsor. There is no obvious specialty choice in your list for quiet professionalism: courtesy, skill, and humble service — so I chose Coaching/Mentorship. 
Please consider either broadening the specialties or listing explanations of what they mean in the specialty list. It would be very helpful. Thank you.

**Comment by jhandel** [comment]
This field is free form.. while there is a long list of options they are not required.. We will look at a way to make that more clear in the UI.
