### ISSUE TITLE
Does membership renew automatically

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#299]
I noticed that my membership was expired in AMP and there was a membership renewal link. After clicking on the link and confirming mine was renewed for another year, I’m not sure if there is an interlink or if I have to send it in. 

Please confirm behavior and make it clear what someone should do.

**Comment by jhandel** [comment]
There is currently no automated integration.. Society has historically not shared a method to enable that.

Please submit your updated membership to the Secretary.
