### ISSUE TITLE
Authorizing marshals cache not clearing

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#301]
Apple, safari, private mode. 
Request combat Archery 
Clear activity type
Request rapier
List of marshals is still the combat Archery marshals 

(Pug observing the issue.   Nicaize submitting because ¯_(ツ)_/¯  )

**Comment by jhandel** [comment]
This query is not cached, though it was worth double checking that clearning did clear.. 

could not reproduced this issue:
Tested the above browser on a Mac & iPhone, both normal and private.
Tested also with Mac Edge/Chrome as well

Did notice that "Armored Combat Archery" and "Rapier Combat Archery" have the same list of marshals and so this may be a case where the user switched between the two forms of combat archery...
