### ISSUE TITLE
Date Crawls when submitting report

### ISSUE THREAD

**Issue by AnsteorraMarshalWebAdmin** [Ansteorra/KMP#31]
https://apps.ansteorra.org/kmp_dev/activities/reports/authorizations?validOn=2024-06-17&amp;activities=&amp;activities%5B%5D=1&amp;activities%5B%5D=2&amp;activities%5B%5D=10&amp;activities%5B%5D=3&amp;activities%5B%5D=4&amp;activities%5B%5D=5&amp;activities%5B%5D=6&amp;activities%5B%5D=7

**Comment by jhandel** [comment]
Resolved in commit 8ebfa6b
