### ISSUE TITLE
Getting error screen upon authorization request

### ISSUE THREAD

**Issue by BillPerkinsSca** [Ansteorra/KMP#45]
Upon request for armored combat auth to **Admin von Admin**, I go tthe following output

[Deprecated (8192) ](javascript:void(0);): Creation of dynamic property Activities\Mailer\ActivitiesMailer::$appSettings is deprecated [in /home/vscribe/apps.ansteorra.org/kmp_dev/plugins/Activities/src/Mailer/ActivitiesMailer.php, line 14]
[Warning (512) ](javascript:void(0);): Unable to emit headers. Headers sent in file=/home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php line=37 [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 65]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 159]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 192]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 192]

**Comment by BillPerkinsSca** [comment]
I am getting the same kind of error screen when **Admin von Admin** approves the auth request

[Deprecated (8192) ](javascript:void(0);): Creation of dynamic property Activities\Mailer\ActivitiesMailer::$appSettings is deprecated [in /home/vscribe/apps.ansteorra.org/kmp_dev/plugins/Activities/src/Mailer/ActivitiesMailer.php, line 14]
[Warning (512) ](javascript:void(0);): Unable to emit headers. Headers sent in file=/home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php line=37 [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 65]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 159]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 192]
[Warning (2) ](javascript:void(0);): Cannot modify header information - headers already sent by (output started at /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Error/Renderer/HtmlErrorRenderer.php:37) [in /home/vscribe/apps.ansteorra.org/kmp_dev/vendor/cakephp/cakephp/src/Http/ResponseEmitter.php, line 192]

**Comment by jhandel** [comment]
also fixed with commit [bce1cea](https://github.com/Ansteorra/KMP/commit/bce1ceaee4e4f9e388071bf3f1e151eb1d9970e4)
